enum EDME_Tasks_EventType
{
	KILL = 0,
	ZONE_ENTER = 1,
	ZONE_LEAVE = 2,
	ITEM_ACQUIRED = 3,
	ITEM_LOST = 4,
	CRAFT = 5,
	ACTION_USED = 6,
	INTERACT = 7,
	PLAYER_DIED = 8,
	PLAYER_CONNECTED = 9,
	PLAYER_DISCONNECTED = 10,
	EXTRACT = 11,
	HANDOVER = 12,
	BOSS_KILL = 13,
	TIMER_TICK = 14,
	TRADER_PROXIMITY = 15,
	SIGNAL_USED = 16,
	GROUP_UPDATE = 17
}
