enum EDME_Tasks_OriginType
{
	UNKNOWN = 0,
	WORLD_LOOT = 1,
	INFECTED_DROP = 2,
	AI_DROP = 3,
	BOSS_DROP = 4,
	EVENT_REWARD = 5,
	QUEST_REWARD = 6,
	TRADER_PURCHASE = 7,
	PLAYER_TRADE = 8,
	ADMIN_SPAWN = 9,
	CRAFTED = 10
}
